services:
  # =========================
  # BACKEND (SPRING BOOT)
  # =========================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: tago-backend
    env_file:
      - ./backend/.env

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      JWT_SECRET: ${JWT_SECRET}

      APP_UPLOAD_DIR: /app/uploads/images/
      APP_BASE_URL: http://localhost:8080
    volumes:
        - ./backend:/app
        - /app/target
        - maven_cache:/root/.m2
        - ./uploads:/app/uploads

    depends_on:
      db:
        condition: service_healthy

    restart: unless-stopped

    stdin_open: true
    tty: true

    networks:
      - tago-network

  # =========================
  # FRONTEND DEV (BUN + VITE)
  # =========================
  frontend:
    image: oven/bun:1.3.13

    container_name: tago-frontend
    env_file:
      - ./frontend/.env

    working_dir: /app

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:8080

    command: sh -c "bun install && bun run dev --host 0.0.0.0"

    depends_on:
      - backend

    restart: unless-stopped

    stdin_open: true
    tty: true

    networks:
      - tago-network

  # =========================
  # POSTGRES DATABASE
  # =========================
  db:
    image: postgres:17-alpine

    container_name: tago-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

    networks:
      - tago-network

  # =========================
  # PGADMIN
  # =========================
  pgadmin:
    image: dpage/pgadmin4:latest

    container_name: tago-pgadmin

    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    ports:
      - "8081:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    depends_on:
      db:
        condition: service_healthy

    networks:
      - tago-network

networks:
  tago-network:
    driver: bridge

volumes:
  db_data:
  maven_cache:
  frontend_node_modules:
  pgadmin_data: