spring:
  application:
    name: backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/pbo_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  task:
    scheduling:
      enabled: true

  jackson:
    serialization:
      indent-output: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB


server:
  port: 8080

google:
  client:
    id: ${VITE_GOOGLE_CLIENT_ID}

jwt:
  secret: ${JWT_SECRET}
  expiration: 900000

logging:
  level:
    org.springframework.security: INFO

app:
  upload:
    dir: ${APP_UPLOAD_DIR:/app/uploads/images/}
  base-url: ${APP_BASE_URL:http://localhost:8080}