spring:
  application:
    name: backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tago_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      indent-output: true

server:
  port: 8080

google:
  client:
    id: ${VITE_GOOGLE_CLIENT_ID}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

logging:
  level:
    org.springframework.security: INFO